region = ""
KeyName = ""
VPC = "<VPC-ID>"
PrivateSubnets = ["<subnet1-id>","<subnet2-id>","<2 or more for HA>"]
NuToken = ""
PSPID = ""
instanceType = "r4.large"
alias = "PSP"
namespace = "nubeva.internal"
